### ISSUE TITLE
Numeric keys in json keys causes problems with sync (either cli or receiving end?)

### ISSUE THREAD

**Issue by rundis** [locize/locize-cli#23]
I had a json translation file with nested structure like the following

```
"errors": {
  "401": "Not authorized",
  "404": "Page not found"
}
```
When running the sync command the first time it added the keys as expected in locize.io. But trying to download the namespace as nested json I got an json with lots of null keys in an array. Discovered it when the sync command reported "removing 498 keys from xyz". I only had like 40 keys in total. Somewhere along the line numeric keys isn't handled nicely, might not be this project. Hard for me to tell though.

```
"errors": [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    ...
```

**Comment by jamuhl** [comment]
Hi Magnus,

The problem lies deep in how flat/unflatten works -> converting keys like errors.401 back to a nested JSON structure. Having a `.` and number value afterwards tells that function to treat that as an array -> therefore filling up that errors array with a lot of nulls until the 401 value.

The simplest way to avoid this treatment as an array is adding one key to errors not being a number, like:

"errors": {
  “keep”: “will stop it from handle it as array”,
  "401": "Not authorized",
  "404": "Page not found"
}
Hope this helps to fix this problem on your side.

Best, Jan
locize.com <http://locize.com/>

**Comment by rundis** [comment]
Thx for the quick response Jan!

There is some sorting of keys going on during sync as well, so I feel the safest bet is to avoid key names which may get duck-typed to something else during processing/transformations in locize. Haven't tried "true", "null" or "undefined", they might work fine, but I'm not overly tempted to take the chance.   

"401" is arguably not necessarily a translator person friendly name anyways 😄 

cheers
-magnus
