### ISSUE TITLE
if you change the values of existing keys in the reference language, it will not change them in locize (to change the existing values you have to change it directly in locize)

### ISSUE THREAD

**Issue by YUFENGWANG** [locize/locize-cli#31]
Since local reference language is `master`,  if we modify some keys value in local repo, we should keep `locize` data up to date with local repo by using cli. there is no need to modify on `locize` by hand directly.

**Comment by adrai** [comment]
Hi!
I don't get exactly what your issue is... can you describe a bit more what you are trying to do?
Wich commands (and arguments) are you using to achieve which goal?

fyi: do you already know the argument `--compare-modification-time true` ? - This can be useful if you want to take into account the modification time while comparing the namespace content between local and remote
